/* eslint-disable react/no-unescaped-entities */

import { Metadata } from "next";
import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";
import SideBar from "./components/SideBar";

/* eslint-disable @next/next/no-img-element */
export const metadata: Metadata = {
  title: "Search : OpenTable",
  description: "Generated by create next app",
};

const Search = () => {
  return (
    <main>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SideBar />
        <div className="w-5/6">
          <RestaurantCard />
        </div>
      </div>
    </main>
  );
};

export default Search;
