/* eslint-disable react/no-unescaped-entities */
import { Metadata } from "next";
import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";
import SideBar from "./components/SideBar";
import { PRICE, PrismaClient } from "@prisma/client";

// /* eslint-disable @next/next/no-img-element */
export const metadata: Metadata = {
  title: "Search : OpenTable",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();
const fetchFilteredRests = async (
  city: string | undefined,
  cuisine: string | undefined,
  price: PRICE | undefined
) => {
  const select = {
    id: true,
    name: true,
    main_image: true,
    location: true,
    price: true,
    cuisine: true,
    slug: true,
    reviews:true
  };
  if (!city) return prisma.restaurant.findMany({ select });
  const restaurants = prisma.restaurant.findMany({
    where: {
      location: {
        name: {
          equals: city.toLowerCase(),
        },
      },
      cuisine: {
        name: {
          equals: cuisine,
        },
      },
      price: {
        equals: price,
      },
    },
    select,
  });

  return restaurants;
};

const fetchLocations = async () => {
  return prisma.location.findMany();
};
const fetchCuisines = async () => {
  return prisma.cuisine.findMany();
};

const Search = async ({
  searchParams,
}: {
  searchParams: { city?: string; cuisine?: string; price?: PRICE };
}) => {
  const restaurants = await fetchFilteredRests(
    searchParams.city,
    searchParams.cuisine,
    searchParams.price
  );
  const locations = await fetchLocations();
  const cuisines = await fetchCuisines();

  return (
    <main>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SideBar
          searchParams={searchParams}
          locations={locations}
          cuisines={cuisines}
        />
        <div className="w-5/6">
          {restaurants.length ? (
            restaurants.map((restaurant, index) => {
              return <RestaurantCard restaurant={restaurant} key={index} />;
            })
          ) : (
            <p>sorry , we found no restaurants in this area</p>
          )}
        </div>
      </div>
    </main>
  );
};

export default Search;
