import RestaurantNavBar from "./components/RestaurantNavBar";
import Title from "./components/Title";
import Rating from "./components/Rating";
import Description from "./components/Description";
import Images from "./components/Images";
import Reviews from "./components/Reviews";
import ReservationCard from "./components/ReservationCard";
import { Metadata } from "next";
import { PrismaClient } from "@prisma/client";
 export interface restaurantSlug {
  id: number;
  name: string;
  description: string;
  images: string[];
  slug: string;
}
const prisma = new PrismaClient();
const fetchRestaurantSlug = async (slug: string): Promise<restaurantSlug> => {
  const restaurantSlug = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      id: true,
      name: true,
      description: true,
      images: true,
      slug: true,
    },
  });
  if (!restaurantSlug) throw new Error();
  return restaurantSlug;
};
export const metadata: Metadata = {
  title: "Milestones Grill",
  description: "Generated by create next app",
};

const RestaurantDetails = async ({ params }: { params: { slug: string } }) => {
  const restaurantSlug = await fetchRestaurantSlug(params.slug);

  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavBar slug={restaurantSlug.slug} />
        <Title restaurantSlug={restaurantSlug} />
        <Rating  />
        <Description restaurantSlug={restaurantSlug} />
        <Images restaurantSlug={restaurantSlug} />
        <Reviews  />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
};

export default RestaurantDetails;
